### PR TITLE
Provide build flag to disable compilation of libyang dependent interfaces

### PR DESCRIPTION
**Pull request by vivekrnv**
#### Why i did it
libswsscommon depends on libyang deb. libyang is deprecated in bookworm. This wouldn't be a problem for buildimage because libyang is compiled from source in buildimage. 

However, this is causing a problem in upgrading one of our app-extensions to bookworm. This app-extension is built separately and not part of buildimage infra. 

Thus provide a build flag to disable compilation of libyang dependent interfaces such as DecoratorTable etc. Please note, there is no change in the default behavior

#### How did i verify
<Build with dep profile>

```
vkarri@6c5cda5d64fa:/sonic/src/sonic-swss-common$ debuild -b -us -uc -Pnopython2,noyangmod 
vkarri@6c5cda5d64fa:/sonic/src$ sudo dpkg -i libswsscommon_1.0.0_amd64.deb vkarri@6c5cda5d64fa:/sonic/src$ sudo dpkg -i python3-swsscommon_1.0.0_amd64.deb 
vkarri@6c5cda5d64fa:/sonic/src$ python3 -c "from swsscommon.swsscommon import DecoratorSubscriberStateTable" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'DecoratorSubscriberStateTable' from 'swsscommon.swsscommon' (/usr/lib/python3/dist-packages/swsscommon/swsscommon.py) 
vkarri@6c5cda5d64fa:/sonic/src$ python3 -c "from swsscommon.swsscommon import DecoratorTable" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'DecoratorTable' from 'swsscommon.swsscommon' (/usr/lib/python3/dist-packages/swsscommon/swsscommon.py) 
vkarri@6c5cda5d64fa:/sonic/src$ python3 -c "from swsscommon.swsscommon import YangDefaultDecorator" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'YangDefaultDecorator' from 'swsscommon.swsscommon' (/usr/lib/python3/dist-packages/swsscommon/swsscommon.py) 

vkarri@6c5cda5d64fa:/sonic/src$ python3 -c "from swsscommon.swsscommon import SubscriberStateTable, ProducerStateTable, Table, DBConnector"
```

**Default Behavior:**

```
vkarri@6c5cda5d64fa:/sonic$ make -f slave.mk target/debs/bookworm/python3-swsscommon_1.0.0_amd64.deb-install
vkarri@6c5cda5d64fa:/sonic$ python3 -c "from swsscommon.swsscommon import DecoratorSubscriberStateTable, DecoratorTable, YangDefaultDecorator"
vkarri@6c5cda5d64fa:/sonic$
```

### CODE REVIEW

File: configure.ac [hunk 1]
```diff
@@ -37,8 +37,16 @@ AC_ARG_ENABLE(python2,
...
+AC_ARG_ENABLE(yang-modules,
+[  --enable-yang-modules   Generate classes that depend on libyang],
+[case "${enableval}" in
+	yes) yang-modules=true ;;
+	no)  yang-modules=false ;;
+	*) AC_MSG_ERROR(bad value ${enableval} for --enable-yang-modules) ;;
+esac],[yang-modules=true])
 AM_CONDITIONAL(DEBUG, test x$debug = xtrue)
 AM_CONDITIONAL(PYTHON2, test x$python2 = xtrue)
+AM_CONDITIONAL(YANGMODS, test x$yang-modules = xtrue)
```
Comment (saiarcot895) [inline configure.ac:49]: The `-` might not be allowed to be part of a bash variable, which is why the build is failing, because YANG-related code is no longer getting compiled. See also https://dev.azure.com/mssonic/build/_build/results?buildId=468556&view=logs&j=a5b8631f-d2a8-5bf4-c5b7-ed5dd46e146c&t=e747c951-66f6-56b8-ce31-6c6f08969189&l=177

Comment (vivekrnv) [reply configure.ac:49]: Thanks for noticing, will update

**Review by saiarcot895 — APPROVED** [review]
